include /etc/nginx/router-generated/hosts.conf;

server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/errors;
    location / {
        try_files /unknown-host.html =404;
    }
}
