"""Render Compose + nginx fragments from inventory + per-repo service contracts."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from ..config.paths import GENERATED_DIRNAME
from ..models.contract import ServiceContract, load_app_file, registry_path
from ..models.inventory import App, Stack

logger = logging.getLogger(__name__)

class StackRenderer:
    def __init__(self, stack: Stack) -> None:
        self.stack = stack

    @property
    def generated_root(self) -> Path:
        return self.stack.root / GENERATED_DIRNAME

    def compose_apps_path(self) -> Path:
        return self.generated_root / "compose.apps.yaml"

    def router_hosts_path(self) -> Path:
        return self.generated_root / "nginx" / "router" / "hosts.conf"

    def gate_tls_dir(self) -> Path:
        return self.generated_root / "nginx" / "gate-tls"

    def load_all_contracts(self) -> dict[str, ServiceContract]:
        out: dict[str, ServiceContract] = {}
        for app in self.stack.apps:
            _, contract = load_app_file(
                registry_path(self.stack.root, app.name),
                expect_name=app.name,
            )
            out[app.name] = contract
        return out

    def render(self, contracts: Optional[dict[str, ServiceContract]] = None) -> None:
        resolved = contracts if contracts is not None else self.load_all_contracts()
        for app in self.stack.apps:
            if app.name not in resolved:
                raise KeyError(f"missing contract for {app.name!r}")
            self._validate_app_contract(app, resolved[app.name])

        self.generated_root.mkdir(parents=True, exist_ok=True)
        (self.generated_root / "nginx" / "router").mkdir(parents=True, exist_ok=True)
        self.gate_tls_dir().mkdir(parents=True, exist_ok=True)

        self.compose_apps_path().write_text(
            self._compose_apps_yaml(resolved), encoding="utf-8"
        )
        self.router_hosts_path().write_text(
            self._router_hosts_conf(resolved), encoding="utf-8"
        )
        for app in self.stack.apps:
            tls_path = self.gate_tls_dir() / f"{app.name}.conf"
            tls_path.write_text(
                self._gate_tls_conf(app, resolved[app.name]), encoding="utf-8"
            )
        keep = {f"{a.name}.conf" for a in self.stack.apps}
        for path in self.gate_tls_dir().glob("*.conf"):
            if path.name not in keep:
                path.unlink()
                logger.info("removed stale generated TLS snippet %s", path.name)

        logger.info(
            "rendered %s apps → %s",
            len(self.stack.apps),
            self.generated_root.relative_to(self.stack.root),
        )

    def _validate_app_contract(self, app: App, contract: ServiceContract) -> None:
        if app.source in {"git", "local"} and not contract.build_context:
            raise ValueError(
                f"{app.name}: contract [spec.build].context is required when source={app.source}"
            )
        if app.source == "docker" and contract.build_context:
            logger.debug(
                "%s: source=docker ignores [spec.build] (image comes from inventory)",
                app.name,
            )

    def _compose_apps_yaml(self, contracts: dict[str, ServiceContract]) -> str:
        if not self.stack.apps:
            return (
                "# Generated by `raft render` — do not edit.\n"
                "# Source: ~/.raft/state/apps/*.yaml (applied App manifests)\n"
                "services: {}\n"
            )

        lines: list[str] = [
            "# Generated by `raft render` — do not edit.",
            "# Source: ~/.raft/state/apps/*.yaml (applied App manifests)",
            "services:",
            "  router:",
            "    depends_on:",
        ]
        for app in self.stack.apps:
            lines.append(f"      {app.name}:")
            lines.append("        condition: service_healthy")

        for app in self.stack.apps:
            c = contracts[app.name]
            lines.append(f"  {app.name}:")
            if app.source == "docker":
                lines.append(f"    image: {app.compose_pin_image}")
            else:
                ctx = (app.abs_path(self.stack.root) / (c.build_context or ".")).resolve()
                try:
                    rel = ctx.relative_to(self.stack.root.resolve())
                except ValueError as exc:
                    raise ValueError(
                        f"{app.name}: build context {ctx} is outside raft data home"
                    ) from exc
                build_path = rel.as_posix()
                if c.dockerfile:
                    lines.append("    build:")
                    lines.append(f"      context: ./{build_path}")
                    lines.append(f"      dockerfile: {c.dockerfile}")
                else:
                    lines.append(f"    build: ./{build_path}")
            lines.append("    expose:")
            lines.append(f'      - "{c.port}"')
            probe = c.probe_path if c.probe_path.startswith("/") else f"/{c.probe_path}"
            lines.append("    healthcheck:")
            lines.append(
                f'      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:{c.port}{probe}"]'
            )
            lines.append("      interval: 2s")
            lines.append("      timeout: 2s")
            lines.append("      retries: 15")
            lines.append("      start_period: 2s")
            lines.append("    restart: unless-stopped")
            lines.append("    deploy:")
            lines.append("      resources:")
            lines.append("        limits:")
            lines.append(f'          cpus: "{c.cpus_limit}"')
            lines.append(f"          memory: {c.memory_limit}")
            lines.append("        reservations:")
            lines.append(f'          cpus: "{c.cpus_reservation}"')
            lines.append(f"          memory: {c.memory_reservation}")
        lines.append("")
        return "\n".join(lines)

    def _router_hosts_conf(self, contracts: dict[str, ServiceContract]) -> str:
        blocks: list[str] = [
            "# Generated by `raft render` — do not edit.",
            "",
        ]
        for app in self.stack.apps:
            blocks.append(f"include /etc/nginx/upstreams/{app.name}.conf;")
        blocks.append("")
        for app in self.stack.apps:
            c = contracts[app.name]
            names = " ".join(c.server_names(app.public_host))
            blocks.extend(
                [
                    "server {",
                    "    listen 80;",
                    f"    server_name {names};",
                    "",
                    "    location / {",
                    f"        proxy_pass http://{app.name}_upstream;",
                    "        proxy_set_header Host $host;",
                    "        proxy_set_header X-Real-IP $remote_addr;",
                    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                    "        proxy_set_header X-Forwarded-Proto $scheme;",
                    "        proxy_connect_timeout 3s;",
                    "        proxy_read_timeout 30s;",
                    "    }",
                    "}",
                    "",
                ]
            )
        return "\n".join(blocks)

    def _gate_tls_conf(self, app: App, contract: ServiceContract) -> str:
        names = " ".join(contract.server_names(app.public_host))
        return (
            f"# Generated by raft render — PEMs: certs/{app.name}/origin.{{pem,key}}\n"
            "server {\n"
            "    listen 443 ssl;\n"
            f"    server_name {names};\n"
            "\n"
            f"    ssl_certificate     /etc/nginx/certs/{app.name}/origin.pem;\n"
            f"    ssl_certificate_key /etc/nginx/certs/{app.name}/origin.key;\n"
            "\n"
            "    include /etc/nginx/gate/proxy_router.inc;\n"
            "}\n"
        )
