"""Edge exposure handlers — one per ``ports[].expose`` mode."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Protocol

from raft.errors import OperatorError

from ...config.settings import EdgeConfig
from ...models.app import App
from ...models.manifest import AppSpec
from ...models.ports import PortSpec


@dataclass
class EdgeFragments:
    router_includes: List[str] = field(default_factory=list)
    router_servers: List[str] = field(default_factory=list)
    gate_http: List[str] = field(default_factory=list)
    gate_stream: List[str] = field(default_factory=list)
    gate_tls: Dict[str, str] = field(default_factory=dict)
    upstreams: Dict[str, str] = field(default_factory=dict)
    host_publish: List[str] = field(default_factory=list)
    expose_ports: List[int] = field(default_factory=list)

    def merge(self, other: "EdgeFragments") -> None:
        self.router_includes.extend(other.router_includes)
        self.router_servers.extend(other.router_servers)
        self.gate_http.extend(other.gate_http)
        self.gate_stream.extend(other.gate_stream)
        self.gate_tls.update(other.gate_tls)
        self.upstreams.update(other.upstreams)
        self.host_publish.extend(other.host_publish)
        self.expose_ports.extend(other.expose_ports)


class EdgeHandler(Protocol):  # pragma: no cover
    def contribute(
        self,
        app: App,
        spec: AppSpec,
        port: PortSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments: ...


@dataclass(frozen=True)
class HttpEdge:
    def contribute(
        self,
        app: App,
        spec: AppSpec,
        port: PortSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments:
        upstream = f"{app.name}_{port.name}"
        filename = f"{app.name}-{port.name}.conf"
        names = " ".join(spec.server_names(app.public_host))
        return EdgeFragments(
            router_includes=[f"include /etc/nginx/upstreams/{filename};"],
            router_servers=[
                "server {",
                "    listen 80;",
                f"    server_name {names};",
                "",
                "    location / {",
                f"        proxy_pass http://{upstream};",
                "        proxy_set_header Host $host;",
                "        proxy_set_header X-Real-IP $remote_addr;",
                "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "        proxy_set_header X-Forwarded-Proto $scheme;",
                "        proxy_connect_timeout 3s;",
                "        proxy_read_timeout 30s;",
                "    }",
                "}",
                "",
            ],
            upstreams={
                filename: (
                    "# Managed by raft — do not hand-edit while deploying.\n"
                    f"upstream {upstream} {{\n"
                    f"    server {app.name}:{port.container_port};\n"
                    "}\n"
                )
            },
            expose_ports=[port.container_port],
        )


@dataclass(frozen=True)
class TlsEdge:
    def contribute_app(
        self,
        app: App,
        spec: AppSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments:
        if spec.tls != "origin":
            return EdgeFragments()
        if edge.https is None:
            raise OperatorError(
                f"{app.name}: tls=origin requires edge.https in settings.yaml.\n"
                f"Fix: set edge.https (e.g. 443) in ~/.raft/settings.yaml, then: raft render"
            )
        names = " ".join(spec.server_names(app.public_host))
        body = (
            f"# Generated by raft render — PEMs: certs/{app.name}/origin.{{pem,key}}\n"
            "server {\n"
            "    listen 443 ssl;\n"
            f"    server_name {names};\n"
            "\n"
            f"    ssl_certificate     /etc/nginx/certs/{app.name}/origin.pem;\n"
            f"    ssl_certificate_key /etc/nginx/certs/{app.name}/origin.key;\n"
            "\n"
            "    include /etc/nginx/gate/proxy_router.inc;\n"
            "}\n"
        )
        return EdgeFragments(gate_tls={f"{app.name}.conf": body})


@dataclass(frozen=True)
class StreamEdge:
    def contribute(
        self,
        app: App,
        spec: AppSpec,
        port: PortSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments:
        declared = edge.declared_stream_ports()
        public = port.public_port
        assert public is not None
        if public not in declared:
            raise OperatorError(
                f"{app.name}: ports[{port.name!r}] publicPort {public} is not "
                f"declared in settings edge.streams "
                f"(known: {sorted(declared) or 'none'}).\n"
                f"Fix: add the port under edge.streams in ~/.raft/settings.yaml, "
                f"then: raft render && raft gate recreate"
            )
        stream = declared[public]
        if stream.protocol != port.protocol:
            raise OperatorError(
                f"{app.name}: ports[{port.name!r}] protocol {port.protocol!r} "
                f"does not match edge.streams entry {stream.name!r} "
                f"({stream.protocol!r}).\n"
                f"Fix: align protocol in .raft/app.yaml and ~/.raft/settings.yaml, "
                f"then: raft render"
            )
        upstream = f"{app.name}_{port.name}"
        filename = f"{app.name}-{port.name}.conf"
        listen = f"{public}" if port.protocol == "tcp" else f"{public} udp"
        proxy_proto = "\n    proxy_protocol on;" if port.proxy_protocol else ""
        server = (
            f"upstream {upstream} {{\n"
            f"    server {app.name}:{port.container_port};\n"
            "}\n"
            "\n"
            "server {\n"
            f"    listen {listen};{proxy_proto}\n"
            f"    proxy_pass {upstream};\n"
            "}\n"
        )
        return EdgeFragments(
            gate_stream=[f"# {app.name}/{port.name}\n{server}"],
            expose_ports=[port.container_port],
        )


@dataclass(frozen=True)
class HostEdge:
    def contribute(
        self,
        app: App,
        spec: AppSpec,
        port: PortSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments:
        public = port.public_port
        assert public is not None
        proto = "" if port.protocol == "tcp" else f"/{port.protocol}"
        return EdgeFragments(
            host_publish=[f'"{public}:{port.container_port}{proto}"'],
            expose_ports=[port.container_port],
        )


EDGE_HANDLERS: Dict[str, EdgeHandler] = {
    "http": HttpEdge(),
    "stream": StreamEdge(),
    "host": HostEdge(),
}


def handler_for(expose: str) -> EdgeHandler:
    try:
        return EDGE_HANDLERS[expose]
    except KeyError as exc:
        raise KeyError(f"no edge handler for expose={expose!r}") from exc
