server {
    listen 80 default_server;
    server_name _;

    include /etc/nginx/gate/proxy_router.inc;
}

include /etc/nginx/gate-tls/*.conf;

server {
    listen 443 ssl default_server;
    server_name _;
    ssl_reject_handshake on;
}
