"""Origin TLS gate snippets (``spec.tls: origin``)."""

from __future__ import annotations

from dataclasses import dataclass

from raft.errors import OperatorError

from ....config.settings_types import EdgeConfig
from ....models.app import App
from ....models.manifest import AppSpec
from .fragments import EdgeFragments


@dataclass(frozen=True)
class TlsEdge:
    def contribute_app(
        self,
        app: App,
        spec: AppSpec,
        *,
        edge: EdgeConfig,
    ) -> EdgeFragments:
        if spec.tls != "origin":
            return EdgeFragments()
        if edge.https is None:
            raise OperatorError(
                f"{app.name}: tls=origin requires edge.https in settings.yaml.\n"
                f"Fix: set edge.https (e.g. 443) in ~/.raft/settings.yaml, then: raft render"
            )
        body = self._tls_server_body(app, spec)
        return EdgeFragments(gate_tls={f"{app.name}.conf": body})

    @staticmethod
    def _tls_server_body(app: App, spec: AppSpec) -> str:
        names = " ".join(spec.server_names(app.public_host))
        return (
            f"# Generated by raft render — PEMs: certs/{app.name}/origin.{{pem,key}}\n"
            "server {\n"
            "    listen 443 ssl;\n"
            f"    server_name {names};\n"
            "\n"
            f"    ssl_certificate     /etc/nginx/certs/{app.name}/origin.pem;\n"
            f"    ssl_certificate_key /etc/nginx/certs/{app.name}/origin.key;\n"
            "\n"
            "    include /etc/nginx/gate/proxy_router.inc;\n"
            "}\n"
        )
