"""Gate TLS snippets for ``spec.tls: origin`` and ``spec.tls: acme``."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from raft.errors.cta import OperatorError
from raft.acme.paths import AcmePaths

from raft.config.settings_types import EdgeConfig
from raft.models.app import App
from raft.models.manifest import AppSpec
from .fragments import EdgeFragments


@dataclass(frozen=True)
class TlsEdge:
    def contribute_app(
        self,
        app: App,
        spec: AppSpec,
        *,
        edge: EdgeConfig,
        data_home: Path,
    ) -> EdgeFragments:
        if spec.tls == "origin":
            return self._origin_fragments(app, spec, edge)
        if spec.tls == "acme":
            return self._acme_fragments(app, spec, edge, data_home)
        return EdgeFragments()

    def _origin_fragments(self, app: App, spec: AppSpec, edge: EdgeConfig) -> EdgeFragments:
        if edge.https is None:
            raise OperatorError(
                f"{app.name}: tls=origin requires edge.https in settings.yaml.\n"
                f"Fix: set edge.https (e.g. 443) in ~/.raft/settings.yaml, then: raft render"
            )
        body = self._tls_server_body(app, spec, stem="origin")
        return EdgeFragments(gate_tls={f"{app.name}.conf": body})

    def _acme_fragments(
        self,
        app: App,
        spec: AppSpec,
        edge: EdgeConfig,
        data_home: Path,
    ) -> EdgeFragments:
        self.require_acme_edge(app, edge)
        if not AcmePaths(data_home).live_material_present(app.name):
            return EdgeFragments()
        body = self._tls_server_body(app, spec, stem="acme")
        return EdgeFragments(gate_tls={f"{app.name}.conf": body})

    @staticmethod
    def require_acme_edge(app: App, edge: EdgeConfig) -> None:
        if edge.http is None:
            raise OperatorError(
                f"{app.name}: tls=acme requires edge.http in settings.yaml "
                f"(HTTP-01 challenge on port 80).\n"
                f"Fix: set edge.http (e.g. 80) in ~/.raft/settings.yaml, then: raft render"
            )
        if edge.https is None:
            raise OperatorError(
                f"{app.name}: tls=acme requires edge.https in settings.yaml.\n"
                f"Fix: set edge.https (e.g. 443) in ~/.raft/settings.yaml, then: raft render"
            )

    @staticmethod
    def _tls_server_body(app: App, spec: AppSpec, *, stem: str) -> str:
        names = " ".join(spec.server_names(app.public_host))
        return (
            f"# Generated by raft render — PEMs: certs/{app.name}/{stem}.{{pem,key}}\n"
            "server {\n"
            "    listen 443 ssl;\n"
            f"    server_name {names};\n"
            "\n"
            f"    ssl_certificate     /etc/nginx/certs/{app.name}/{stem}.pem;\n"
            f"    ssl_certificate_key /etc/nginx/certs/{app.name}/{stem}.key;\n"
            "\n"
            "    include /etc/nginx/gate/proxy_router.inc;\n"
            "}\n"
        )
