"""Durable operator home under ``~/.raft/`` (override with ``RAFT_DATA_HOME``)."""

from __future__ import annotations

import os
import shutil
from importlib.metadata import PackageNotFoundError, requires as distribution_requires
from pathlib import Path
from typing import Optional

from raft.errors import OperatorError

DATA_HOME_ENV = "RAFT_DATA_HOME"
SETTINGS_FILENAME = "settings.yaml"
GENERATED_DIRNAME = "generated"
DEPLOY_DIRNAME = "deploy"
APPS_DIRNAME = "apps"
CERTS_DIRNAME = "certs"
LOGS_DIRNAME = "logs"
STATE_DIR = Path("state") / "apps"
LOCKS_DIR = Path("state") / "locks"

_TEMPLATE_FILES = ("compose.yaml",)
_TEMPLATE_DIRS = ("nginx", "controller")
# Synced into ~/.raft/controller/raft so Compose can build raft-controller.
_CONTROLLER_BUILD_DIR = "controller"
_CONTROLLER_PACKAGE_DIR = "raft"
_CONTROLLER_PYPROJECT = "pyproject.toml"


def raft_home() -> Path:
    override = os.environ.get(DATA_HOME_ENV)
    if override is not None:
        if not override.strip():
            raise OperatorError(
                f"{DATA_HOME_ENV} is set but empty.\n"
                f"Fix: unset {DATA_HOME_ENV} or set it to an absolute path (e.g. ~/.raft)"
            )
        return Path(override).expanduser().resolve()
    return (Path.home() / ".raft").resolve()


def settings_path(home: Optional[Path] = None) -> Path:
    return (home or raft_home()) / SETTINGS_FILENAME


def _bundled_share() -> Path:
    return Path(__file__).resolve().parent.parent / "share"


def find_package_root(start: Optional[Path] = None) -> Path:
    bundled = _bundled_share()
    if _is_package_root(bundled):
        return bundled
    here = (start or Path.cwd()).resolve()
    for candidate in [here, *here.parents]:
        if _is_package_root(candidate):
            return candidate
    pkg = Path(__file__).resolve().parent
    for candidate in [pkg, *pkg.parents]:
        if _is_package_root(candidate):
            return candidate
    raise OperatorError(
        "could not find raft package templates (compose.yaml + nginx/).\n"
        "Fix: reinstall raft (`raft update`) or run from a checkout that includes src/raft/share/"
    )


def _is_package_root(candidate: Path) -> bool:
    return (candidate / "compose.yaml").is_file() and (candidate / "nginx").is_dir()


def ensure_raft_home(
    home: Optional[Path] = None,
    *,
    package_root: Optional[Path] = None,
) -> Path:
    root = home if home is not None else raft_home()
    root.mkdir(parents=True, exist_ok=True)
    for rel in (
        GENERATED_DIRNAME,
        DEPLOY_DIRNAME,
        APPS_DIRNAME,
        CERTS_DIRNAME,
        LOGS_DIRNAME,
        str(STATE_DIR),
        str(LOCKS_DIR),
        f"{GENERATED_DIRNAME}/nginx/gate-tls",
        f"{GENERATED_DIRNAME}/nginx/gate-http",
        f"{GENERATED_DIRNAME}/nginx/gate-stream",
        f"{GENERATED_DIRNAME}/nginx/router",
        f"{GENERATED_DIRNAME}/nginx/upstreams",
    ):
        (root / rel).mkdir(parents=True, exist_ok=True)

    pkg = package_root if package_root is not None else find_package_root()
    sync_product_templates(root, pkg)

    stub = root / GENERATED_DIRNAME / "compose.apps.yaml"
    if not stub.is_file():
        stub.write_text(
            "# Generated by `raft render` — do not edit.\nservices: {}\n",
            encoding="utf-8",
        )
    edge_stub = root / GENERATED_DIRNAME / "compose.edge.yaml"
    if not edge_stub.is_file():
        edge_stub.write_text(
            "# Generated by `raft render` — gate published ports from settings edge:\n"
            "services:\n"
            "  raft-gate:\n"
            "    ports:\n"
            '      - "80:80"\n'
            '      - "443:443"\n',
            encoding="utf-8",
        )
    return root


def sync_product_templates(home: Path, package_root: Path) -> None:
    for name in _TEMPLATE_FILES:
        src = package_root / name
        if not src.is_file():
            raise FileNotFoundError(f"missing package template: {src}")
        dest = home / name
        shutil.copy2(src, dest)
    for name in _TEMPLATE_DIRS:
        src = package_root / name
        if not src.is_dir():
            raise FileNotFoundError(f"missing package template dir: {src}")
        dest = home / name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest)
    _sync_controller_package(home, package_root)


def _sync_controller_package(home: Path, package_root: Path) -> None:
    """Copy the installable ``raft`` package into the controller build context.

    ``package_root`` is ``…/raft/share``; the Python package lives one level up.
    Fake test package roots without a parent package are skipped for the package
    tree, but ``pyproject.toml`` is still synced for the image build.
    """
    raft_src = package_root.parent
    if (raft_src / "__init__.py").is_file():
        dest = home / _CONTROLLER_BUILD_DIR / _CONTROLLER_PACKAGE_DIR
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(
            raft_src,
            dest,
            ignore=shutil.ignore_patterns(
                "__pycache__", "*.pyc", "*.pyo", ".pytest_cache"
            ),
        )
    _sync_controller_pyproject(home, package_root)


def _find_raft_pyproject(package_root: Path) -> Optional[Path]:
    """Walk parents for the raft project ``pyproject.toml`` (checkout / editable)."""
    for directory in (package_root, *package_root.parents):
        candidate = directory / _CONTROLLER_PYPROJECT
        if not candidate.is_file():
            continue
        text = candidate.read_text(encoding="utf-8")
        if 'name = "raft"' in text or "name = 'raft'" in text:
            return candidate
    return None


def _sync_controller_pyproject(home: Path, package_root: Path) -> None:
    """Place ``pyproject.toml`` in the controller build context for ``uv pip compile``.

    Prefer the repo file when present; otherwise synthesize deps from the installed
    ``raft`` distribution (``uv tool install`` / wheel) so Docker still builds.
    """
    dest_dir = home / _CONTROLLER_BUILD_DIR
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / _CONTROLLER_PYPROJECT
    src = _find_raft_pyproject(package_root)
    if src is not None:
        shutil.copy2(src, dest)
        return
    _write_controller_pyproject_from_installed(dest)


def _write_controller_pyproject_from_installed(dest: Path) -> None:
    try:
        reqs = distribution_requires("raft")
    except PackageNotFoundError as exc:
        raise FileNotFoundError(
            "controller build needs pyproject.toml (checkout) or an installed raft "
            "distribution to read dependencies"
        ) from exc
    if not reqs:
        raise FileNotFoundError(
            "installed raft distribution has no requires; cannot build controller deps"
        )
    deps: list[str] = []
    for raw in reqs:
        if ";" in raw:
            name_part, marker = raw.split(";", 1)
            if "extra" in marker:
                continue
            deps.append(name_part.strip())
        else:
            deps.append(raw.strip())
    if not deps:
        raise FileNotFoundError(
            "installed raft distribution has no main dependencies for controller"
        )
    lines = [
        "[project]",
        'name = "raft-controller-deps"',
        'version = "0"',
        'requires-python = ">=3.8"',
        "dependencies = [",
    ]
    for dep in deps:
        escaped = dep.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{escaped}",')
    lines.append("]")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
