apiVersion: raft/v1
kind: App
metadata:
  name: example-app
spec:
  publicHost: app.example.com
  source: git
  repo: git@github.com:example/consumer-app.git
  ref: main
  path: apps/example-app
  www: true
  tls: off
  ports:
    - name: http
      containerPort: 80
      expose: http
  build:
    context: .
    dockerfile: Dockerfile
  readiness:
    type: http
    port: http
    path: /
