"""Compose apps YAML builder for ``raft render``."""

from __future__ import annotations

from ...models.app import App
from ...models.manifest import AppSpec
from ...models.stack import Stack
from .edge import EdgeFragments
from ..deploy.readiness import ReadinessStrategy


def compose_str(value: str) -> str:
    """Quote a Compose scalar when it contains reserved characters."""
    if value == "":
        return '""'
    if any(ch in value for ch in ":\n#{}[]&*!|>%@`'\"\\") or value.strip() != value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


class ComposeAppsYaml:
    """Build ``generated/compose.apps.yaml`` text from applied apps + edge fragments."""

    def __init__(self, stack: Stack) -> None:
        self.stack = stack

    def build(self, specs: dict[str, AppSpec], fragments: EdgeFragments) -> str:
        if not self.stack.apps:
            return (
                "# Generated by `raft render` — do not edit.\n"
                "# Source: ~/.raft/state/apps/*.yaml (applied App manifests)\n"
                "services: {}\n"
            )
        host_by_app, expose_by_app = self._port_maps(specs)
        compose_by_name = {a.name: a.compose_id for a in self.stack.apps}
        lines = self._header_lines()
        for app in self.stack.apps:
            self._append_service(
                lines,
                app,
                specs[app.name],
                host_by_app=host_by_app,
                expose_by_app=expose_by_app,
                compose_by_name=compose_by_name,
            )
        lines.append("")
        return "\n".join(lines)

    def _header_lines(self) -> list[str]:
        lines = [
            "# Generated by `raft render` — do not edit.",
            "# Source: ~/.raft/state/apps/*.yaml (applied App manifests)",
            "services:",
            f"  {self.stack.router}:",
            "    depends_on:",
        ]
        for app in self.stack.apps:
            lines.append(f"      {app.compose_id}:")
            lines.append("        condition: service_healthy")
        return lines

    def _port_maps(
        self, specs: dict[str, AppSpec]
    ) -> tuple[dict[str, list[str]], dict[str, list[int]]]:
        host_by_app: dict[str, list[str]] = {a.name: [] for a in self.stack.apps}
        expose_by_app: dict[str, list[int]] = {a.name: [] for a in self.stack.apps}
        for app in self.stack.apps:
            for port in specs[app.name].ports:
                expose_by_app[app.name].append(port.container_port)
                if port.expose == "host":
                    public = port.public_port
                    assert public is not None
                    proto = "" if port.protocol == "tcp" else f"/{port.protocol}"
                    host_by_app[app.name].append(
                        f'"{public}:{port.container_port}{proto}"'
                    )
        return host_by_app, expose_by_app

    def _append_service(
        self,
        lines: list[str],
        app: App,
        c: AppSpec,
        *,
        host_by_app: dict[str, list[str]],
        expose_by_app: dict[str, list[int]],
        compose_by_name: dict[str, str],
    ) -> None:
        lines.append(f"  {app.compose_id}:")
        self._append_image_or_build(lines, app, c)
        self._append_ports(lines, app, host_by_app, expose_by_app)
        self._append_env(lines, c)
        self._append_volumes(lines, c)
        self._append_depends(lines, c, compose_by_name)
        lines.extend(ReadinessStrategy.from_spec(c).healthcheck_compose_lines())
        lines.append("    restart: unless-stopped")
        self._append_resources(lines, c)

    def _append_image_or_build(self, lines: list[str], app: App, c: AppSpec) -> None:
        if app.source == "docker":
            lines.append(f"    image: {app.compose_pin_image}")
            return
        ctx = (app.abs_path(self.stack.root) / (c.build_context or ".")).resolve()
        try:
            rel = ctx.relative_to(self.stack.root.resolve())
        except ValueError as exc:
            raise ValueError(
                f"{app.name}: build context {ctx} is outside raft data home"
            ) from exc
        build_path = rel.as_posix()
        if c.dockerfile:
            lines.append("    build:")
            lines.append(f"      context: ./{build_path}")
            lines.append(f"      dockerfile: {c.dockerfile}")
        else:
            lines.append(f"    build: ./{build_path}")

    @staticmethod
    def _append_ports(
        lines: list[str],
        app: App,
        host_by_app: dict[str, list[str]],
        expose_by_app: dict[str, list[int]],
    ) -> None:
        lines.append("    expose:")
        for port_num in sorted(set(expose_by_app[app.name])):
            lines.append(f'      - "{port_num}"')
        host_ports = host_by_app[app.name]
        if not host_ports:
            return
        lines.append("    ports:")
        for entry in host_ports:
            lines.append(f"      - {entry}")

    @staticmethod
    def _append_env(lines: list[str], c: AppSpec) -> None:
        if c.env_file:
            lines.append("    env_file:")
            lines.append(f"      - {c.env_file}")
        if not c.env:
            return
        lines.append("    environment:")
        for key, value in c.env:
            lines.append(f"      {key}: {compose_str(value)}")

    @staticmethod
    def _append_volumes(lines: list[str], c: AppSpec) -> None:
        if not c.volumes:
            return
        lines.append("    volumes:")
        for vol in c.volumes:
            suffix = ":ro" if vol.read_only else ""
            lines.append(f"      - {vol.host_path}:{vol.container_path}{suffix}")

    @staticmethod
    def _append_depends(
        lines: list[str], c: AppSpec, compose_by_name: dict[str, str]
    ) -> None:
        deps = [compose_by_name[d] for d in c.depends_on if d in compose_by_name]
        if not deps:
            return
        lines.append("    depends_on:")
        for dep in deps:
            lines.append(f"      {dep}:")
            lines.append("        condition: service_started")

    @staticmethod
    def _append_resources(lines: list[str], c: AppSpec) -> None:
        lines.append("    deploy:")
        lines.append("      resources:")
        lines.append("        limits:")
        lines.append(f'          cpus: "{c.cpus_limit}"')
        lines.append(f"          memory: {c.memory_limit}")
        lines.append("        reservations:")
        lines.append(f'          cpus: "{c.cpus_reservation}"')
        lines.append(f"          memory: {c.memory_reservation}")
